### ISSUE TITLE
Update the angular-1-gulp-babel repo with updated verbiage

### ISSUE THREAD

**Issue by kellishouts** [AirshipCMS/angular-1-gulp-babel.airshipcms.io#2]
Add a `cms-content` directory outside of compartments to this repo, and copy the docs from the angular-1 repo, and add in proper verbiage that is difference for this repo.

Note that I've changed some fields in the angular-1 repo, this repo will have to be updated as well.
all the richtext areas are now textareas. (since it is easier to maintain markup in these git md files, and just copypasta the output to the cms).

Add in the syntax highlighter from the angular-1 repo.

Update the `assets` directory that is outside compartments (or add one if there is none), and include all the assets from the assets directory from the angular-1 repo.

Copy the markup from the pages to the CMS, and edit out the link icons.

Once this is done, I can send to Jon to review so we can close out this project.

**Comment by fobabett** [comment]
starting

**Comment by fobabett** [comment]
done
