### ISSUE TITLE
Angular 1 / Angular 1 Gulp Babel Edits

### ISSUE THREAD

**Issue by kellishouts** [AirshipCMS/angular-1-gulp-babel.airshipcms.io#3]
- [x] **Angular 1** does this repo use gulp? need to add Gulp to list on README.md & homepage:
![image](https://user-images.githubusercontent.com/1865400/28729247-86db9c06-7367-11e7-97f8-a305107acaba.png)

- [x] **Angular 1 Gulp Babel** update the title in the upper left to be "Angular 1.x + Gulp + Babel + Airship CMS"
![image](https://user-images.githubusercontent.com/1865400/28729297-adb39fc2-7367-11e7-8c9e-e271b33322e9.png)

- [x] **Angular 1 Gulp Babel** fix README.md & homepage text typo:
![image](https://user-images.githubusercontent.com/1865400/28729314-c126bc06-7367-11e7-8ca2-e099a4b7f46c.png)

- [x] **Angular 1 Gulp Babel** fix Styling.md / styling page & Angular Tutorial.md / Angular Tutorial page. You have gulpfile instructions listed on the styling page and angular tutorial page. Is only one of these files is correct? Or do they need to be modified into one gulpfile? Maybe wording needs to be updated in the styling section to use the gulp/babel gulpfile, and just highlight/point out the relevant parts that relate to styling? Revise as appropriate.

- [x] **Angular 1.x + Gulp + Babel + Airship CMS** Revise the `<title>` in the `<head>` to be **Angular 1.x + Gulp + Babel + Airship CMS**

- [x] What is the name of the syntax highlighter component you are using? I want to recommend some color adjustments, though I want to know what is possible. Post a link to the component so I can look it up :)

**Comment by fobabett** [comment]
starting

**Comment by fobabett** [comment]
syntax highlighter being used is PrismJS. http://prismjs.com/

**Comment by fobabett** [comment]
done

**Comment by kellishouts** [comment]
- [x] Can you apply the 'OKAIDIA' theme for all projects, instead of the theme being used now?

**Comment by fobabett** [comment]
starting

**Comment by fobabett** [comment]
done

**Comment by kellishouts** [comment]
- [x] React App: This is really huge for some reason, and it should read "React"
![image](https://user-images.githubusercontent.com/1865400/28800356-0bbc7c9c-75e8-11e7-842e-9c6afb8d6670.png)

- [x] React App: Remove line on hover:
![image](https://user-images.githubusercontent.com/1865400/28800482-7f8d7536-75e8-11e7-98fc-17f0ff9b4e5e.png)

- [x] Angular-1: Fix the Syntax Highlighting to match the theme shown on react. You might have to undo whatever the background color is (it looks grey in Angular-1 and is black in React App)
![image](https://user-images.githubusercontent.com/1865400/28800405-3f1c0bca-75e8-11e7-87e4-302867e5a872.png)
![image](https://user-images.githubusercontent.com/1865400/28800410-42cf3d82-75e8-11e7-89fa-ab9141a681c7.png)

**Comment by fobabett** [comment]
done
